// Assemble store-ready builds of the extension.
//
//   node build.mjs chrome    -> ./chrome-build   (Chrome Web Store)
//   node build.mjs firefox   -> ./firefox-build  (Firefox AMO / Android)
//   node build.mjs           -> both
//
// The working manifest.json stays dev-friendly (localhost origins for the local
// practice fixture, the legacy behaviour content script). This packager produces
// CLEAN store builds from it: only the gov.uk host, no localhost, no legacy
// content.js, a packaged build flag, and the per-browser background shape. Single
// source of truth = manifest.json; everything else is copied as-is because the
// detection/autofill/watch logic is browser-agnostic.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const VERSION = "1.3.0";

// Runtime files the SHIPPED product uses. Note: content.js (legacy activity
// telemetry), dev-fixture/, test/, and the build scripts are intentionally excluded.
const RUNTIME_FILES = [
  "background.js",
  "refresh-schedule.js",
  "roster.js",
  "dvsa-heuristics.js",
  "selectors.js",
  "watch-match.js",
  "fastpath-util.js",
  "watch-content.js",
  "fastpath-content.js",
  "popup.html",
  "popup.js",
  "options.html",
  "options.js",
];
const ICONS = ["icons/icon16.png", "icons/icon48.png", "icons/icon128.png"];

const source = JSON.parse(readFileSync(path.join(dir, "manifest.json"), "utf8"));

function noLocalhost(list) {
  return (list || []).filter((s) => !s.includes("localhost"));
}

// Produce a clean, store-ready manifest from the dev manifest.
function cleanManifest() {
  const m = structuredClone(source);
  m.version = VERSION;
  m.host_permissions = noLocalhost(m.host_permissions);
  m.content_scripts = (m.content_scripts || [])
    .filter((cs) => !(cs.js || []).includes("content.js")) // drop legacy telemetry
    .map((cs) => ({ ...cs, matches: noLocalhost(cs.matches) }))
    .filter((cs) => (cs.matches || []).length > 0);
  return m;
}

function build(target) {
  const outDir = path.join(dir, `${target}-build`);
  const manifest = cleanManifest();

  if (target === "firefox") {
    // Firefox (esp. Android): event-page background, not a service worker.
    delete manifest.background.service_worker;
    // roster.js + refresh-schedule.js define globals (AvailoRoster, nextRefreshDelay)
    // that background.js uses, so they must load first.
    manifest.background = { scripts: ["refresh-schedule.js", "roster.js", "background.js"] };
    manifest.browser_specific_settings = {
      gecko: { id: "availo-fastpath@availo.app", strict_min_version: "120.0" },
    };
  }
  // chrome: keep background.service_worker as authored.

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(path.join(outDir, "icons"), { recursive: true });
  writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  for (const f of [...RUNTIME_FILES, ...ICONS]) {
    copyFileSync(path.join(dir, f), path.join(outDir, f));
  }
  // Overwrite the build flag + dev constants so packaged builds hide dev-only
  // affordances and contain no localhost anywhere.
  writeFileSync(
    path.join(outDir, "build-config.js"),
    [
      "// Generated by build.mjs — packaged store build.",
      "const AVAILO_PACKAGED = true;",
      'const AVAILO_PRACTICE_URL = "";',
      'const AVAILO_DEV_HOST_MATCH = "";',
      "",
    ].join("\n"),
  );

  // Sanity: no localhost anywhere in the shipped package (manifest or code).
  for (const f of ["manifest.json", "build-config.js", ...RUNTIME_FILES]) {
    if (f.endsWith(".png")) continue;
    const text = readFileSync(path.join(outDir, f), "utf8");
    if (text.includes("localhost")) throw new Error(`${target}: localhost leaked into ${f}`);
  }

  console.log(`✓ ${target}-build ready (v${VERSION})`);
}

const arg = (process.argv[2] || "all").toLowerCase();
const targets = arg === "all" ? ["chrome", "firefox"] : [arg];
for (const t of targets) {
  if (t !== "chrome" && t !== "firefox") throw new Error(`unknown target: ${t}`);
  build(t);
}
console.log("Zip the build folder's contents to submit (Chrome Web Store / addons.mozilla.org).");
