// Official DVSA car practical driving test centre names, sourced from DVSA's own
// published statistics (table DRT122A, "Practical car pass rates by gender, month
// and DTC", April 2025 - March 2026 sheet): https://www.gov.uk/government/statistical-data-sets/car-driving-test-data-by-test-centre
// Used only to power a suggestions list in the options page — the Test centre field
// stays free text, so a centre missing here (or renamed since) can still be typed.
const DVSA_CENTRES = [
  "Aberdeen North", "Aberdeen South (Cove)", "Aberfeldy", "Abergavenny", "Aberystwyth (Park Avenue)",
  "Airdrie", "Alness", "Alnwick", "Arbroath", "Ashfield", "Ashford (Kent)", "Atherton (Manchester)",
  "Aylesbury", "Ayr", "Bala", "Banbury", "Banff", "Bangor", "Barking (Tanner Street)", "Barnet (London)",
  "Barnsley", "Barnstaple", "Barrow In Furness", "Barry", "Basildon", "Basingstoke", "Bedford",
  "Belvedere (London)", "Benbecula Island", "Berwick-On-Tweed", "Beverley LGV", "Birmingham (Cocks Moors)",
  "Birmingham (Garretts Green)", "Birmingham (Kings Heath)", "Birmingham (Kingstanding)",
  "Birmingham (Shirley)", "Birmingham (South Yardley)", "Bishopbriggs", "Bishops Stortford",
  "Blackburn with Darwen", "Blackpool", "Bletchley", "Blyth", "Bodmin", "Bolton (Manchester)",
  "Borehamwood (London)", "Boston", "Bradford (Heaton)", "Bradford (Thornbury)", "Brecon",
  "Bredbury (Manchester)", "Brentwood (London)", "Bridgend", "Bridlington", "Bristol (Avonmouth)",
  "Bristol (Kingswood)", "Brodick (Isle of Arran)", "Bromley (London)", "Buckie", "Burgess Hill",
  "Burton on Trent", "Bury (Manchester)", "Bury St Edmunds", "Buxton", "Callander", "Camborne",
  "Cambridge (Brookmount Court)", "Campbeltown", "Canterbury", "Cardiff (Llanishen)", "Cardigan",
  "Carlisle", "Carlisle LGV (Cars)", "Carmarthen", "Castle Douglas", "Chadderton", "Cheetham Hill (Manchester)",
  "Chelmsford", "Cheltenham", "Chertsey (London)", "Chester", "Chesterfield", "Chichester",
  "Chingford (London)", "Chippenham", "Chorley", "Clacton-on-Sea", "Colchester", "Coventry", "Crawley",
  "Crewe", "Cumnock", "Darlington", "Derby (Alvaston)", "Doncaster", "Dorchester", "Dudley", "Dumbarton",
  "Dumfries", "Dundee", "Dunfermline (Vine)", "Dunoon", "Duns", "Durham", "East Kilbride", "Eastbourne",
  "Edinburgh (Currie)", "Edinburgh (Musselburgh)", "Elgin", "Enfield (Brancroft Way)",
  "Enfield (Innova Business Park)", "Erith (London)", "Exeter", "Farnborough", "Featherstone",
  "Folkestone", "Forfar", "Fort William", "Fraserburgh", "Gairloch", "Galashiels", "Gateshead",
  "Gillingham", "Girvan", "Glasgow (Anniesland)", "Glasgow (Baillieston)", "Glasgow (Shieldhall)",
  "Gloucester", "Golspie", "Goodmayes (London)", "Gosforth", "Grangemouth", "Grantham (Somerby)",
  "Grantown-On-Spey", "Greenford (Horsenden Lane)", "Greenham", "Greenock", "Grimsby Coldwater",
  "Guildford", "Haddington", "Halifax", "Hamilton", "Hartlepool", "Hastings (Ore)", "Hawick",
  "Heckmondwike", "Hendon (London)", "Hereford", "Herne Bay", "Hexham", "Heysham", "High Wycombe",
  "Hinckley", "Hornchurch (London)", "Horsforth", "Huddersfield", "Hull", "Huntly", "Inveraray",
  "Inverness (Longman Drive)", "Inverurie", "Ipswich", "Irvine", "Isle of Mull", "Isle of Skye (Portree)",
  "Isles of Scilly", "Isleworth (Fleming Way)", "Kelso", "Kendal (Oxenholme Road)", "Kettering",
  "Kings Lynn", "Kingussie", "Kirkcaldy", "Knaresborough", "Kyle of Lochalsh", "Lanark", "Launceston",
  "Lee On The Solent", "Leeds (Colton Mill)", "Leeds (Fearnville)", "Leicester (Cannock Street)",
  "Leicester (Wigston)", "Leighton Buzzard (Stanbridge Road)", "Lerwick", "Letchworth", "Lichfield",
  "Lincoln", "Livingston", "Llanelli", "Llantrisant", "Lochgilphead", "Loughborough", "Loughton (London)",
  "Louth", "Lowestoft(Mobbs Way)", "Ludlow", "Luton", "Macclesfield", "Maidstone", "Mallaig", "Malton",
  "Melton Mowbray", "Merthyr Tydfil", "Middlesbrough", "Mill Hill (London)", "Mitcham (London)",
  "Monmouth", "Montrose", "Morden (London)", "Nelson", "Newport (Gwent)", "Newport (Isle of Wight)",
  "Newton Abbot", "Newton Stewart", "Newtown", "Norris Green (Liverpool)", "Northallerton",
  "Northampton", "Northwich", "Norwich (Peachman Way)", "Nottingham (Chilwell)", "Nottingham (Colwick)",
  "Nuneaton", "Oban", "Orkney", "Oswestry", "Oxford (Cowley)", "Paisley", "Peebles", "Pembroke Dock",
  "Penzance", "Perth (Arran Road)", "Peterborough", "Peterhead", "Pinner (London)", "Pitlochry",
  "Plymouth", "Pontefract", "Poole", "Portsmouth", "Preston", "Pwllheli", "Reading", "Redditch",
  "Redhill Aerodrome", "Rhyl", "Rochdale (Manchester)", "Rotherham", "Rothesay", "Rugby",
  "Sale (Manchester)", "Salisbury", "Scarborough", "Scunthorpe", "Sevenoaks", "Sheffield (Handsworth)",
  "Sheffield (Middlewood Road)", "Shrewsbury", "Sidcup (London)", "Skegness", "Skipton", "Slough (London)",
  "Southall (London)", "Southampton (Maybush)", "Southend-on-Sea", "Southport (Liverpool)",
  "Speke (Liverpool)", "St Albans", "St Helens (Liverpool)", "Stafford", "Steeton", "Stevenage",
  "Stirling", "Stoke-On-Trent (Cobridge)", "Stoke-on-Trent (Newcastle-Under-Lyme)", "Stornoway",
  "Stranraer", "Sunderland", "Swansea", "Swindon", "Taunton", "Telford", "Thurso", "Tilbury",
  "Tolworth (London)", "Tottenham", "Trowbridge", "Tunbridge Wells", "Ullapool", "Upton",
  "Uxbridge (London)", "Wakefield", "Wallasey", "Walton LGV", "Wanstead (London)", "Warrington",
  "Warwick (Wedgenock House)", "Watford", "Wednesbury", "Wellingborough", "West Didsbury (Manchester)",
  "West Wickham (London)", "Weston-super-Mare", "Whitby", "Wick", "Widnes", "Winchester", "Wolverhampton",
  "Wood Green (London)", "Worcester", "Workington", "Worksop", "Worthing", "Wrexham", "Yeading (London)",
  "Yeovil", "York",
];

if (typeof self !== "undefined") self.DVSA_CENTRES = DVSA_CENTRES;
if (typeof window !== "undefined") window.DVSA_CENTRES = DVSA_CENTRES;
if (typeof module !== "undefined" && module.exports) module.exports = DVSA_CENTRES;
